/* v1.85: templates, question reuse, custom completion, and printable response copy. */
(function(){
  'use strict';
  var lastReceiptV185=null;
  var FORM_TEMPLATES_V185={
    blank:{name:'空白問卷',description:'從空白內容開始建立',title:'',questions:[]},
    employee:{name:'員工意見調查',description:'了解工作體驗與改善建議',title:'員工意見調查',questions:[{type:'linearScale',title:'您對目前整體工作體驗的滿意程度為何？',required:true,settings:{min:1,max:5,minLabel:'非常不滿意',maxLabel:'非常滿意'}},{type:'multiple',title:'您認為目前最值得改善的項目有哪些？',options:['工作流程','跨部門溝通','工作環境','教育訓練','其他'],required:false},{type:'long',title:'其他建議',required:false}]},
    event:{name:'活動報名',description:'蒐集參加意願與必要資料',title:'活動報名表',questions:[{type:'single',title:'是否參加本次活動？',options:['參加','不參加'],required:true},{type:'short',title:'聯絡電話',required:false,validation:{type:'phone',message:'請輸入正確的電話格式'}},{type:'long',title:'飲食需求或其他備註',required:false}]},
    satisfaction:{name:'滿意度調查',description:'快速蒐集服務或活動回饋',title:'滿意度調查',questions:[{type:'rating',title:'整體滿意度',required:true,settings:{max:5,minLabel:'不滿意',maxLabel:'非常滿意'}},{type:'single',title:'您是否願意再次參加或使用？',options:['願意','不確定','不願意'],required:true},{type:'long',title:'請告訴我們可以改善的地方',required:false}]},
    training:{name:'教育訓練回饋',description:'蒐集課程內容與講師回饋',title:'教育訓練回饋表',questions:[{type:'linearScale',title:'課程內容對工作的實用程度',required:true,settings:{min:1,max:5,minLabel:'幫助有限',maxLabel:'非常實用'}},{type:'linearScale',title:'講師說明是否清楚',required:true,settings:{min:1,max:5,minLabel:'不清楚',maxLabel:'非常清楚'}},{type:'long',title:'希望未來增加哪些課程內容？',required:false}]}
  };
  function templateCardV185(id,t){return '<button type="button" onclick="applyFormTemplateV185(\''+id+'\')"><span class="templateIconV185">'+({blank:'＋',employee:'人',event:'曆',satisfaction:'★',training:'學'}[id]||'表')+'</span><strong>'+esc(t.name)+'</strong><small>'+esc(t.description)+'</small></button>'}
  window.openTemplatePickerV185=function(){document.querySelector('#templatePickerMaskV185')?.remove();document.body.insertAdjacentHTML('beforeend','<div id="templatePickerMaskV185" class="modalMask" style="display:grid"><div class="dialogCard templatePickerCardV185"><div class="modalHeader"><div><h3>選擇問卷範本</h3><p>套用後仍可自由修改題目與設定。</p></div><button class="modalClose" type="button" onclick="closeTemplatePickerV185()">×</button></div><div class="templateGridV185">'+Object.keys(FORM_TEMPLATES_V185).map(function(id){return templateCardV185(id,FORM_TEMPLATES_V185[id])}).join('')+'</div></div></div>');syncAdminModalLockV138()};
  window.closeTemplatePickerV185=function(){document.querySelector('#templatePickerMaskV185')?.remove();syncAdminModalLockV138()};
  window.applyFormTemplateV185=async function(id){var t=FORM_TEMPLATES_V185[id];if(!t)return;if(draftQuestions.length&&!await confirmDialog('套用範本會取代目前題目，確定繼續嗎？','套用範本'))return;draftQuestions=(t.questions||[]).map(function(q){return newQuestion(q.type)&&normalizeQuestion(Object.assign(newQuestion(q.type),q))});$('formTitle').value=t.title||'';closeTemplatePickerV185();formDirty=true;renderQuestionEditor();toast('已套用「'+t.name+'」範本','success')};

  function importableFormsV185(){return forms.filter(function(f){return f.id!==editingId&&(!window.canViewForm||canViewForm(f.id))})}
  window.openQuestionImportV185=function(){var list=importableFormsV185();document.querySelector('#questionImportMaskV185')?.remove();document.body.insertAdjacentHTML('beforeend','<div id="questionImportMaskV185" class="modalMask" style="display:grid"><div class="dialogCard questionImportCardV185"><div class="modalHeader"><div><h3>從既有問卷匯入題目</h3><p>可選擇題目、說明內容或完整區段。</p></div><button class="modalClose" onclick="closeQuestionImportV185()">×</button></div>'+(list.length?'<label>來源問卷<select id="questionImportSourceV185" onchange="renderQuestionImportChoicesV185()">'+list.map(function(f){return '<option value="'+attr(f.id)+'">'+esc(f.title)+'</option>'}).join('')+'</select></label><div id="questionImportChoicesV185"></div><div class="modalActions"><button class="btn" onclick="closeQuestionImportV185()">取消</button><button class="btn primary" onclick="confirmQuestionImportV185()">匯入所選內容</button></div>':'<div class="emptyAnalysis">目前沒有其他可匯入的問卷。</div>')+'</div></div>');if(list.length)renderQuestionImportChoicesV185();syncAdminModalLockV138()};
  window.closeQuestionImportV185=function(){document.querySelector('#questionImportMaskV185')?.remove();syncAdminModalLockV138()};
  window.renderQuestionImportChoicesV185=function(){var id=($('questionImportSourceV185')||{}).value,f=forms.find(function(x){return x.id===id}),box=$('questionImportChoicesV185');if(!box||!f)return;var n=0;box.innerHTML='<div class="questionImportToolsV185"><button class="btn" type="button" onclick="document.querySelectorAll(\'.questionImportCheckV185\').forEach(function(x){x.checked=true})">全部選取</button><span>共 '+normalizeQuestions(f.questions||[]).length+' 個內容項目</span></div><div class="questionImportListV185">'+normalizeQuestions(f.questions||[]).map(function(q,i){if(isAnswerBlockV182(q))n++;var label=isSectionBlockV182(q)?'區段':(q.type==='image'?'說明':'題目 '+n);return '<label><input class="questionImportCheckV185" type="checkbox" value="'+i+'"><span><b>'+label+'</b>'+esc(q.title||'未命名內容')+'</span></label>'}).join('')+'</div>'};
  window.confirmQuestionImportV185=function(){var id=($('questionImportSourceV185')||{}).value,f=forms.find(function(x){return x.id===id});if(!f)return;var selected=[].slice.call(document.querySelectorAll('.questionImportCheckV185:checked')).map(function(x){return Number(x.value)}),source=normalizeQuestions(f.questions||[]),added=selected.map(function(i){var q=JSON.parse(JSON.stringify(source[i]));q.id=(isSectionBlockV182(q)?'section_':'q_')+Date.now()+'_'+Math.random().toString(36).slice(2,7);q.imageStoragePath='';q.contentFiles=[];return normalizeQuestion(q)});draftQuestions=draftQuestions.concat(added);closeQuestionImportV185();formDirty=true;renderQuestionEditor();toast('已匯入 '+added.length+' 個內容項目','success')};

  function ensureCompletionSettingsV185(){var pane=$('editorPaneSettingsV181'),block=pane?.querySelector('.formBlock');if(!block||$('completionMessageV185'))return;block.insertAdjacentHTML('beforeend','<section class="completionSettingsV185"><div><h4>送出完成頁</h4><p>設定填寫者送出後看到的訊息與回覆副本。</p></div><label>完成訊息<textarea id="completionMessageV185" placeholder="感謝您的填寫，我們已收到您的回覆。"></textarea></label><label class="switchLineV185"><input id="showResponseSummaryV185" type="checkbox" checked><span>送出後顯示填寫摘要</span></label><label class="switchLineV185"><input id="allowResponsePrintV185" type="checkbox" checked><span>允許列印或另存填寫副本</span></label></section>')}
  function setCompletionFieldsV185(f){ensureCompletionSettingsV185();$('completionMessageV185').value=f?.completionMessage||'感謝您的填寫，我們已收到您的回覆。';$('showResponseSummaryV185').checked=f?.showResponseSummary!==false;$('allowResponsePrintV185').checked=f?.allowResponsePrint!==false}
  var baseStartNewFormV185=startNewForm;startNewForm=function(){var r=baseStartNewFormV185();setCompletionFieldsV185(null);return r};
  var baseEditFormV185=editForm;editForm=function(id){var r=baseEditFormV185(id),f=forms.find(function(x){return x.id===id});setCompletionFieldsV185(f);return r};
  var baseSaveFormV185=saveForm;saveForm=async function(){var extras={completionMessage:($('completionMessageV185')||{}).value||'',showResponseSummary:!!$('showResponseSummaryV185')?.checked,allowResponsePrint:!!$('allowResponsePrintV185')?.checked,schemaVersion:2};await baseSaveFormV185();if(!formDirty&&activeFormId){await doc('universalForms',activeFormId).set(extras,{merge:true});var f=forms.find(function(x){return x.id===activeFormId});if(f)Object.assign(f,extras)}};

  function receiptHtmlV185(f,answers){return '<div class="responseSummaryV185"><h3>填寫摘要</h3>'+normalizeQuestions(f.questions||[]).filter(isAnswerBlockV182).map(function(q){return '<div><b>'+esc(q.title||'未命名題目')+'</b><span>'+esc(answerText(q,{answers:answers})||'未填')+'</span></div>'}).join('')+'</div>'}
  window.printResponseCopyV185=function(){if(!lastReceiptV185)return;var win=window.open('','_blank');if(!win)return notify('瀏覽器已阻擋新視窗，請允許彈出視窗後再試一次','warn');win.document.write('<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><title>填寫副本</title><style>body{font-family:Arial,"Noto Sans TC",sans-serif;max-width:760px;margin:40px auto;padding:0 24px;color:#17324d}h1{border-bottom:2px solid #2a7c78;padding-bottom:15px}.item{padding:13px 0;border-bottom:1px solid #ddd}.item b{display:block;margin-bottom:6px}.meta{color:#687b8e}</style><body><h1>'+esc(lastReceiptV185.title)+'</h1><p class="meta">填寫時間：'+esc(new Date().toLocaleString('zh-TW'))+'</p>'+lastReceiptV185.items.map(function(x){return '<div class="item"><b>'+esc(x.title)+'</b><span>'+esc(x.answer||'未填')+'</span></div>'}).join('')+'<script>window.onload=function(){window.print()}<\/script></body></html>');win.document.close()};
  var baseSubmitResponseV185=submitResponse;submitResponse=async function(event){var f=activeForm(),answers={};try{answers=collectAnswers(event.target,f)}catch(e){}await baseSubmitResponseV185(event);var card=document.querySelector('.submitSuccessCard');if(!card||!f)return;var message=f.completionMessage||'感謝您的填寫，我們已收到您的回覆。';var p=card.querySelector('p');if(p)p.textContent=message;lastReceiptV185={title:f.title,items:normalizeQuestions(f.questions||[]).filter(isAnswerBlockV182).map(function(q){return {title:q.title,answer:answerText(q,{answers:answers})}})};if(f.showResponseSummary!==false)card.insertAdjacentHTML('beforeend',receiptHtmlV185(f,answers));if(f.allowResponsePrint!==false)card.insertAdjacentHTML('beforeend','<button class="btn" type="button" onclick="printResponseCopyV185()">列印／儲存填寫副本</button>')};

  function installTemplateActionsV185(){ensureCompletionSettingsV185();var head=document.querySelector('#editorPaneContentV181 .questionHead');if(head&&!head.querySelector('.templateActionsV185'))head.insertAdjacentHTML('beforeend','<div class="buttonRow templateActionsV185"><button class="btn" type="button" onclick="openTemplatePickerV185()">套用範本</button><button class="btn" type="button" onclick="openQuestionImportV185()">匯入既有題目</button></div>')}
  document.documentElement.setAttribute('data-product-version','1.85');setTimeout(installTemplateActionsV185,0);
})();
