/* v1.91 unified notification center for invitations, reminders, extensions and results. */
(function(){
  'use strict';
  var types={
    invite:{label:'問卷邀請',prefix:'[問卷通知]',group:'expected'},
    reminder:{label:'未填提醒',prefix:'[填寫提醒]',group:'missing'},
    extension:{label:'期限異動',prefix:'[期限異動]',group:'missing'},
    result:{label:'結果通知',prefix:'[調查結果]',group:'filled'}
  };
  function url(f){return location.href.split('#')[0]+'#form/'+encodeURIComponent(f.id)}
  function people(f,type){var data=completionData(f),group=types[type]?.group||'expected';return(data[group]||[]).filter(function(m){return memberCompanyEmail(m)})}
  function defaults(f,type){var link=url(f),deadline=f.deadline?formatDeadline(f.deadline):'依問卷頁面公告',title=f.title||'問卷';if(type==='reminder')return{subject:'[填寫提醒] '+title+' 尚未完成',body:'您好：\n\n系統顯示您尚未完成「'+title+'」，敬請於 '+deadline+' 前完成填寫。\n\n問卷連結：'+link+'\n\n如已完成填寫，請忽略本信；感謝您的配合。'};if(type==='extension')return{subject:'[期限異動] '+title,body:'您好：\n\n「'+title+'」填寫期限已調整為 '+deadline+'，請於期限前完成填寫。\n\n問卷連結：'+link+'\n\n感謝您的配合。'};if(type==='result')return{subject:'[調查結果] '+title,body:'各位同仁您好：\n\n「'+title+'」調查結果已完成彙整，相關結果請依管理單位公告內容辦理。\n\n感謝您的配合。'};return{subject:'[問卷通知] '+title,body:'各位同仁您好：\n\n為辦理「'+title+'」，敬請於 '+deadline+' 前完成填寫。\n\n問卷連結：'+link+'\n\n感謝您的配合。'}}
  function checked(){return[].slice.call(document.querySelectorAll('.notificationRecipientV191:checked')).map(function(input){var m=members.find(function(x){return x.id===input.value});return m?{department:memberDepartmentName(m),name:m.name||'',email:memberCompanyEmail(m)}:null}).filter(Boolean)}
  function renderRecipients(f,type){var list=people(f,type),box=$('notificationRecipientsV191'),count=$('notificationRecipientCountV191');if(count)count.textContent=list.length+' 人';if(box)box.innerHTML=list.length?list.map(function(m){return'<label><input class="notificationRecipientV191" type="checkbox" value="'+attr(m.id)+'" checked><span>'+esc(memberDepartmentName(m)+'-'+(m.name||''))+'</span></label>'}).join(''):'<p class="emptyStateV191">目前沒有具公司信箱的適用收件者。</p>'}
  window.changeNotificationTypeV191=function(type){var f=activeForm();if(!f)return;var d=defaults(f,type);$('notificationSubjectV191').value=d.subject;$('notificationBodyV191').value=d.body;renderRecipients(f,type)};
  window.toggleNotificationRecipientsV191=function(checkedValue){document.querySelectorAll('.notificationRecipientV191').forEach(function(input){input.checked=checkedValue})};
  window.closeNotificationCenterV191=function(){$('notificationCenterMaskV191')?.remove();if(typeof syncAdminModalLockV138==='function')syncAdminModalLockV138()};
  window.openNotificationCenterV191=function(initialType){var f=activeForm();if(!f)return notify('請先選擇問卷');document.querySelector('#notificationCenterMaskV191')?.remove();var type=types[initialType]?initialType:'invite',d=defaults(f,type);document.body.insertAdjacentHTML('beforeend','<div id="notificationCenterMaskV191" class="modalMask" style="display:grid"><div class="dialogCard notificationCenterV191"><div class="modalHeader"><div><h3>信件通知</h3><p>選擇通知用途、收件者並產出可修改的 EML 郵件。</p></div><button class="modalClose" type="button" onclick="closeNotificationCenterV191()">×</button></div><div class="notificationGridV191"><label>信件類型<select id="notificationTypeV191" onchange="changeNotificationTypeV191(this.value)">'+Object.keys(types).map(function(k){return'<option value="'+k+'" '+(k===type?'selected':'')+'>'+types[k].label+'</option>'}).join('')+'</select></label><label>信件主旨<input id="notificationSubjectV191" value="'+attr(d.subject)+'"></label></div><section class="recipientPanelV191"><div class="recipientHeadV191"><div><b>正本收件者</b><span id="notificationRecipientCountV191"></span></div><div class="buttonRow"><button class="btn" type="button" onclick="toggleNotificationRecipientsV191(true)">全選</button><button class="btn" type="button" onclick="toggleNotificationRecipientsV191(false)">取消全選</button></div></div><div id="notificationRecipientsV191" class="recipientChipsV191"></div></section><label>信件內容<textarea id="notificationBodyV191" rows="10">'+esc(d.body)+'</textarea></label><p class="questionHelp">收件者使用人員管理中的公司信箱；下載後仍可在 Outlook 等郵件軟體修改。</p><div class="modalActions"><button class="btn" type="button" onclick="closeNotificationCenterV191()">取消</button><button class="btn primary" type="button" onclick="downloadNotificationV191()">下載 EML</button></div></div></div>');renderRecipients(f,type);if(typeof syncAdminModalLockV138==='function')syncAdminModalLockV138()};
  window.downloadNotificationV191=function(){var f=activeForm(),recipients=checked();if(!recipients.length)return notify('請至少選擇一位具公司信箱的收件者');try{var count=SurveyNotificationToolsV186.downloadEml({recipients:recipients,subject:$('notificationSubjectV191').value,body:$('notificationBodyV191').value,filename:(f.title||'問卷')+'_'+types[$('notificationTypeV191').value].label});closeNotificationCenterV191();toast('已建立 '+count+' 位收件者的郵件','success')}catch(e){notify(e.message||'郵件建立失敗','error')}};
})();
