/* v1.92 share center: URL, QR, preview, schedule and notification shortcuts. */
(function(){
  'use strict';
  function formUrl(f){return location.href.split('#')[0]+'#form/'+encodeURIComponent(f.id)}
  window.closeShareCenterV192=function(){$('shareCenterMaskV192')?.remove();if(typeof syncAdminModalLockV138==='function')syncAdminModalLockV138()};
  window.copyShareUrlV192=async function(){var value=$('shareUrlV192')?.value||'';try{await navigator.clipboard.writeText(value);toast('問卷網址已複製','success')}catch(e){showCopyDialog('複製問卷網址',value)}};
  window.previewFromShareV192=function(){closeShareCenterV192();showFront()};
  window.openShareNotificationV192=function(){closeShareCenterV192();openNotificationCenterV192('invite')};
  window.openShareCenterV192=function(){if(typeof editMode!=='undefined'&&editMode==='new'&&$('editorPanel')?.classList.contains('active'))return notify('請先建立問卷，再使用分享功能');var f=(editingId&&forms.find(function(x){return x.id===editingId}))||activeForm();if(!f||!f.id)return notify('請先儲存問卷，再使用分享功能');var link=formUrl(f),qr='https://quickchart.io/qr?size=220&margin=1&text='+encodeURIComponent(link),state=typeof stateLabel==='function'?stateLabel(effectiveState(f)):(f.state||'草稿');document.querySelector('#shareCenterMaskV192')?.remove();document.body.insertAdjacentHTML('beforeend','<div id="shareCenterMaskV192" class="modalMask" style="display:grid"><div class="dialogCard shareCenterV192"><div class="modalHeader"><div><h3>分享問卷</h3><p>集中確認網址、QR Code、問卷期間及通知內容。</p></div><button class="modalClose" onclick="closeShareCenterV192()">×</button></div><div class="shareLayoutV192"><section><label>問卷網址<div class="copyFieldV192"><input id="shareUrlV192" readonly value="'+attr(link)+'"><button class="btn primary" type="button" onclick="copyShareUrlV192()">複製網址</button></div></label><dl class="shareScheduleV192"><div><dt>目前狀態</dt><dd>'+esc(state)+'</dd></div><div><dt>開啟時間</dt><dd>'+esc(f.startTime?formatDeadline(f.startTime):'切換為開放後立即開放')+'</dd></div><div><dt>截止時間</dt><dd>'+esc(f.deadline?formatDeadline(f.deadline):'未設定')+'</dd></div></dl><div class="buttonRow"><button class="btn" type="button" onclick="previewFromShareV192()">預覽問卷</button><button class="btn" type="button" onclick="openShareNotificationV192()">建立邀請郵件</button></div></section><aside class="shareQrV192"><img src="'+attr(qr)+'" alt="問卷 QR Code"><b>掃描前往問卷</b><small>QR Code 內容與左側網址相同</small></aside></div><div class="modalActions"><button class="btn" onclick="closeShareCenterV192()">關閉</button></div></div></div>');if(typeof syncAdminModalLockV138==='function')syncAdminModalLockV138()};
})();
